### ISSUE TITLE
Geocoder requirements

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/openjourneyplanner-geocoder#1]
**Imported Datasources**
- [x] Seudullinen osoiteluettelo
- [x] MML kunnat
- [x] Palvelukartta pääkaupunkiseutu
- [x] OSM
- [ ] Valtakunnallinen palvelukartta
- [x] Liikuntapaikat (lipas-service)

**Searchable data**
- Geocoding (position for given text):
  - Address
  - Stop short number
  - Stop long number
  - POI
  - District (kaupunginosa)
  - City
- Reverse geocoding (text for given position)
  - Address

**Search metadata parameters**
- Search modes
  - "Pääkaupunkiseutu tagged": Only search for tagged data for "pääkaupunkiseutu".Note: "Kaupunkiseutu" is not an area on map. It is all data that is tagged for it.
  - "All": Search in all of Finland
- Zoom level
  - Geocoding should take zoom level as parameter. This should affect whether addresses are returned. I.e. on low zoom level only city district or city should be returned.
- True/False whether services (e.g. libraries) should be returned. Check http://dev.hel.fi/servicemap
- How many search results are returned per "result type" (address, poi, ...)

**Matching of search results**
- Match should be full text search. E.g. "man" should match "*man*"
- Match should work with typos. Consider Levenshtein algorithm. 
- Matching should work with "typos" and "suggestions"
- Address search should recognize match without comma before city in search string e.g: "opastinsilta 6 helsinki"
- Address search should recognize match without the name of the city e.g: "linnankoskenkatu 10" finds: "Linnankoskenkatu 10, Helsinki". 

**Language support**
- Support: Finnish and Swedish.
- If UI language is in Swedish: Return results in Swedish
- If UI language is in Any other language: Return results in Finnish

**Returning results**
- No duplicates should be returned if same target is found from multiple datasources.

**Ordering of results**
1) Address
2) POI (e.g. Finlandia house, Tampere)
3) Service (e.g. Library)
4) Stop name
5) Stop number
If same street name exists in multiple times, order is according alphabetic order of city name. e.g. "koivutie  4"  gives first "Koivutie 4, Kirkkonummi".

**Search speed**
- Search should be as fast as possible. One second is too slow, it should be around 100 - 300ms.

**Documentation**
- Document how geocoding is implemented

**Requirements on UI**
- When user clicks on search box, system should immediately show:
1) Favourites. Order these by distance from current location if possible.
2) Previous searches

**Comment by tpievila** [comment]
Elasticsearch performance considerations:

* NIO vs mmap
* geohashing size
* threadpool and queue size
* https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing
* geopoint indexing and precision compression

**Comment by tpievila** [comment]
http://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html for production hardware
